name: "GetOCIDOfResources"
on:
#  schedule:
#    - cron: '*/5 * * * *'
  
 # push:
 #   branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
   inputs:
      envname:
        description: 'source database env name'
        required: true
        type: string
        default: dev
      db-instance-name:
        description: 'source database instance name'
        required: false
        type: string
        default: Thayer_Development
      compartment-name:
       description: 'compartment name to retrieve the DB instance details '
       required: true
       type: string
       default: thayer_dev
      db-subnet-name:
       description: 'DB Instance VCN subnet name '
       required: false
       type: string
       default: ""
      nsg-name:
       description: 'Get NSG ID based on nsg id  '
       required: false
       type: string
       default: ""
      nsg-compartmentid:
       description: 'Get NSG compartment ID  '
       required: false
       type: string
       default: ""
   outputs:
      compartmentocid:
        description: "return compartment ocid"
        value: ${{ jobs.getcompartmentanddbinstanceid.outputs.compartmentocid }}
      dbinstanceocid:
        description: "return db instance ocid"
        value: ${{ jobs.getcompartmentanddbinstanceid.outputs.dbinstanceocid }}
      dbname:
       description: "return db instance name"
       value: ${{ jobs.getcompartmentanddbinstanceid.outputs.dbname }}
      nsgid:
       description: "return nsg id"
       value: ${{ jobs.getcompartmentanddbinstanceid.outputs.nsgid }}
      subnetid:
       description: "return subnet id"
       value: ${{ jobs.getcompartmentanddbinstanceid.outputs.subnetid }}
       
     
jobs:
  getcompartmentanddbinstanceid:
    runs-on: self-hosted
    environment: ${{ inputs.envname || 'dev' }} 
    name: CompartmentAndDBInstIDRetrieval
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
      #RUNNER_TOOL_CACHE: /thayer/envs/dev
      #AGENT_TOOLSDIRECTORY: /thayer/envs/dev
      DB_ENV: ${{ inputs.envname || 'dev' }}
      DB_INST: ${{ inputs.db-instance-name || 'Thayer_Development' }}
      
      OCI_COMPARTMENT_NAME: ${{  inputs.compartment-name || 'thayer_dev' }}
      NSG_NAME: ${{ inputs.nsg-name || 'thayerdev_nsg' }}
      NSG_CMPID: ${{ inputs.nsg-compartmentid || 'OCI_USEast_Thayer_Core_Infra' }}
      SUBNET_NAME: ${{ inputs.db-subnet-name || 'thayer_dev_net' }}
     
    steps:
      - name: Workspace Location
        run: echo $GITHUB_WORKSPACE
      
      - name: Get Compartment ID
        if: "${{ inputs.compartment-name != '' }}"
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: getcompartmentid
        with:
          command: ' oci  iam compartment  list --name "${{ env.OCI_COMPARTMENT_NAME }}"'
          #query: "data[?name=='${{ env.OCI_COMPARTMENT_NAME }}'].id"
          silent: false
      - name: Add Compartment OCID To the Env 
        if: "${{ inputs.compartment-name != '' }}"
        id: compartmentocidoutput
        env:
         cmpid: ${{ steps.getcompartmentid.outputs.output }}
        run: |
          echo "test****"$cmpid
          echo "cmpid=$cmpid" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        
          echo "${{ steps.getcompartmentid.outputs.output }} | jq ."
          retid=$(echo ${{ steps.getcompartmentid.outputs.output }} | jq .[0])
         
          echo "retid"$retid
          echo "DB_COMPARTMENTID=$(echo $retid)" >> $GITHUB_ENV
          echo "DB_COMPARTMENTID=$(echo $retid)" >> $GITHUB_OUTPUT
          echo "DB INSTANCE NAME****" ${{ inputs.db-instance-name }}
      - name: Get Source DB ID 
        if: "${{ env.DB_INST != '' }}"
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: getsourcedbid
        with:
          command: ' oci db autonomous-database list --compartment-id ${{ env.DB_COMPARTMENTID }} --display-name ${{ env.DB_INST }}'
          #query: "data[?'display-name'=='${{ env.DB_INST }}'].id"
          silent: false
        
      - name: Add Source DB OCID To the Env 
        id: getsourcedbidoutput
        if: "${{ env.DB_INST != '' }}"
        env:
         srcid: ${{ steps.getsourcedbid.outputs.output }}
        run: |
         
          echo "srcid***"$srcid 
          #cat $GITHUB_OUTPUT
          echo ${{ steps.getsourcedbid.outputs.output }} | jq .data[0].id
          retid=$(echo ${{ steps.getsourcedbid.outputs.output }} | jq .data[0].id)
          
          echo "DB_INST_ID=$(echo $retid)" >> $GITHUB_ENV
          echo "DB_INST_ID=$(echo $retid)" >> $GITHUB_OUTPUT
          dbname=$(echo ${{ steps.getsourcedbid.outputs.output }} | jq '.data[0]."db-name"')
          echo "DB_NAME=$(echo $dbname)" >> $GITHUB_ENV
          echo "DB_NAME=$(echo $dbname)" >> $GITHUB_OUTPUT
          cat $GITHUB_ENV
      - name: Get SUBNET ID 
        if: "${{ inputs.subnet-name != '' }}"
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: getsubnetid
        with:
          command: ' oci  network subnet  list --compartment-id ${{ env.DB_COMPARTMENTID }}  --display-name ${{ env.SUBNET_NAME }}'
          #query: "data[?name=='${{ env.NAME }}'].id"
          silent: false
      - name: Add SUBNET OCID To the Env 
        id: getsubnetdetails
        if: "${{ inputs.subnet-name != '' }}"
        env:
         subnetid: ${{ steps.getsubnetid.outputs.output }}
        run: |
         
          echo "subnet***"$subnetid 
          #cat $GITHUB_OUTPUT
          echo ${{ steps.subnetid.outputs.output }} | jq .data[0].id
          retid=$(echo ${{ steps.submetid.outputs.output }} | jq .data[0].id)
          
          echo "SUBNET_ID=$(echo $retid)" >> $GITHUB_ENV
          echo "SUBNET_ID=$(echo $retid)" >> $GITHUB_OUTPUT
          
          cat $GITHUB_ENV
      - name: Get NSG ID 
        if: "${{ inputs.nsg-name != '' }}"
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: getnsgid
        with:
          command: ' oci  network nsg  list --compartment-id ${{ env.NSG_CMPID }}  --display-name ${{ env.NSG_NAME }} '
          #query: "data[?name=='${{ env.NSG_NAME }}'].id"
          silent: false
      - name: Add NSG OCID To the Env 
        id: getnsgdetails
        if: "${{ inputs.nsg-name != '' }}"
        env:
         nsgid: ${{ steps.getnsgid.outputs.output }}
        run: |
         
          echo "nsg***"$nsgid 
          #cat $GITHUB_OUTPUT
          echo ${{ steps.nsgid.outputs.output }} | jq .data[0].id
          retid=$(echo ${{ steps.nsgid.outputs.output }} | jq .data[0].id)
          
          echo "NSG_ID=$(echo $retid)" >> $GITHUB_ENV
          echo "NSG_ID=$(echo $retid)" >> $GITHUB_OUTPUT
          
          cat $GITHUB_ENV
    outputs:
      compartmentocid: ${{ steps.compartmentocidoutput.outputs.DB_COMPARTMENTID }}
      dbinstanceocid: ${{ steps.getsourcedbidoutput.outputs.DB_INST_ID }}
      dbname: ${{ steps.getsourcedbidoutput.outputs.DB_NAME }}
      nsgid: ${{ steps.getsourcedbidoutput.outputs.NSG_ID }}
      subnetid: ${{ steps.getsourcedbidoutput.outputs.SUBNET_ID }}
      
      
     
    

